name: Validate C++

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/lint-cpp.yml"
      - "**/*.h"
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.c"
      - "**/*.mm"
    paths-ignore:
      - "node_modules"
      - "**/node_modules"
  pull_request:
    paths:
      - ".github/workflows/lint-cpp.yml"
      - "**/*.h"
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.c"
      - "**/*.mm"
    paths-ignore:
      - "node_modules"
      - "**/node_modules"

jobs:
  lint:
    name: Check clang-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "package/android/src/main/cpp"
          - "package/cpp"
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "18"
          check-path: ${{ matrix.path }}
